// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// boss_objective_cpp
double boss_objective_cpp(IntegerVector NT, IntegerVector NC, int normalization);
RcppExport SEXP _MOBACO_boss_objective_cpp(SEXP NTSEXP, SEXP NCSEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type NT(NTSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NC(NCSEXP);
    Rcpp::traits::input_parameter< int >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(boss_objective_cpp(NT, NC, normalization));
    return rcpp_result_gen;
END_RCPP
}
// boss_delta_cpp
double boss_delta_cpp(IntegerVector NT, IntegerVector NC, IntegerVector off, IntegerVector code_out, IntegerVector code_in, int normalization);
RcppExport SEXP _MOBACO_boss_delta_cpp(SEXP NTSEXP, SEXP NCSEXP, SEXP offSEXP, SEXP code_outSEXP, SEXP code_inSEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type NT(NTSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NC(NCSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type off(offSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type code_out(code_outSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type code_in(code_inSEXP);
    Rcpp::traits::input_parameter< int >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(boss_delta_cpp(NT, NC, off, code_out, code_in, normalization));
    return rcpp_result_gen;
END_RCPP
}
// calc_boss_fitness_cpp
NumericVector calc_boss_fitness_cpp(NumericVector ind, IntegerMatrix bin_mat, IntegerVector k_vec, IntegerVector T_int, IntegerVector C_int, int nT_total, int nC_total, int min_per_group, int normalization);
RcppExport SEXP _MOBACO_calc_boss_fitness_cpp(SEXP indSEXP, SEXP bin_matSEXP, SEXP k_vecSEXP, SEXP T_intSEXP, SEXP C_intSEXP, SEXP nT_totalSEXP, SEXP nC_totalSEXP, SEXP min_per_groupSEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ind(indSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type bin_mat(bin_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type k_vec(k_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type T_int(T_intSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type C_int(C_intSEXP);
    Rcpp::traits::input_parameter< int >::type nT_total(nT_totalSEXP);
    Rcpp::traits::input_parameter< int >::type nC_total(nC_totalSEXP);
    Rcpp::traits::input_parameter< int >::type min_per_group(min_per_groupSEXP);
    Rcpp::traits::input_parameter< int >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_boss_fitness_cpp(ind, bin_mat, k_vec, T_int, C_int, nT_total, nC_total, min_per_group, normalization));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MOBACO_boss_objective_cpp", (DL_FUNC) &_MOBACO_boss_objective_cpp, 3},
    {"_MOBACO_boss_delta_cpp", (DL_FUNC) &_MOBACO_boss_delta_cpp, 6},
    {"_MOBACO_calc_boss_fitness_cpp", (DL_FUNC) &_MOBACO_calc_boss_fitness_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_MOBACO(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
