# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Full balance from the bin counts
#'
#' Needed only at the start and after a restart.
#' @keywords internal
boss_objective_cpp <- function(NT, NC, normalization = 0L) {
    .Call(`_MOBACO_boss_objective_cpp`, NT, NC, normalization)
}

#' Change in balance from a 1-exchange
#'
#' @param off       0-based start position of each covariate in the flat vector
#' @param code_out  bin code of the leaving unit, per covariate (1-based)
#' @param code_in   bin code of the entering unit
#' @keywords internal
boss_delta_cpp <- function(NT, NC, off, code_out, code_in, normalization = 0L) {
    .Call(`_MOBACO_boss_delta_cpp`, NT, NC, off, code_out, code_in, normalization)
}

#' Calculate Balance-Coverage Fitness (C++)
NULL

calc_boss_fitness_cpp <- function(ind, bin_mat, k_vec, T_int, C_int, nT_total, nC_total, min_per_group, normalization = 0L) {
    .Call(`_MOBACO_calc_boss_fitness_cpp`, ind, bin_mat, k_vec, T_int, C_int, nT_total, nC_total, min_per_group, normalization)
}

